helm:
  parameters:
  - name: frontend.image.repository
    value: vasu049/dairy-flow-frontend
    forcestring: true
  - name: frontend.image.tag
    value: v1.0.45
    forcestring: true
  - name: backend.image.repository
    value: vasu049/dairy-flow-backend
    forcestring: true
  - name: backend.image.tag
    value: v1.0.45
    forcestring: true
