apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: milk-app-updater
  namespace: argocd
spec:
  namespace: argocd

  applicationRefs:
    - namePattern: milk-app

      images:
        - alias: frontend
          imageName: vasu049/dairy-flow-frontend
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
          manifestTargets:
            helm:
              name: frontend.image.repository
              tag: frontend.image.tag

        - alias: backend
          imageName: vasu049/dairy-flow-backend
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
          manifestTargets:
            helm:
              name: backend.image.repository
              tag: backend.image.tag

  writeBackConfig:
    method: git
    gitConfig:
      branch: main
      writeBackTarget: helmvalues
