apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: milk
type: Opaque
stringData:
  db-username: "{{ .Values.externalDatabase.username }}"
  db-password: "{{ .Values.externalDatabase.password }}"
  jwt-secret: "{{ .Values.jwt.secret }}"
  razorpay-key: "{{ .Values.razorpay.key }}"
  razorpay-secret: "{{ .Values.razorpay.secret }}"
  mail-username: "{{ .Values.mail.username }}"
  mail-password: "{{ .Values.mail.password }}"
